#!/bin/bash
sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate
sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic
sudo docker compose -f docker-compose.production.yml exec backend cp -r /app/collected_static/. /backend_static/static/
sudo docker compose -f docker-compose.production.yml exec backend cp /app/default.png /app/media/users/default.png
sudo docker compose -f docker-compose.production.yml exec backend python manage.py load_from_csv -f ingredients.csv -m Ingredient
sudo docker compose -f docker-compose.production.yml exec backend python manage.py createsuperuser
